FROM eclipse-temurin:25-jre-alpine
RUN addgroup -S mdqr && adduser -S -G mdqr mdqr
WORKDIR /app
COPY --chown=mdqr:mdqr app.jar /app/app.jar
USER mdqr
ENTRYPOINT ["java", \
    "--enable-native-access=ALL-UNNAMED", \
    "-XX:+UseG1GC", \
    "-XX:MaxRAMPercentage=75.0", \
    "-Djava.security.egd=file:/dev/./urandom", \
    "-jar", "/app/app.jar"]
